export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_LEETCODE_ENTRIES = "FETCH_LEETCODE_ENTRIES";
export const DELETE_LEETCODE_ENTRY = "DELETE_LEETCODE_ENTRY";
export const UPDATE_LEETCODE_ENTRIES = "UPDATE_LEETCODE_ENTRIES";